In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Highest _averages - Sheet1.csv")

In [3]:
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
58,Rahmat Shah (AFG),2018-2026,12*,22,1,1013,234,48.23,1901,53.28,3,5,4,123,7
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [4]:
df=df.rename(columns={"Mat":"Matches","NO":"Not_Outs","HS":"Highest_Inns_Score","BF":"Balls_Faced","SR":"Strike_Rate"})

In [5]:
df.head()

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1

In [6]:
df.isnull().any()

Player                False
Span                  False
Matches               False
Inns                  False
Not_Outs              False
Runs                  False
Highest_Inns_Score    False
Ave                   False
Balls_Faced            True
Strike_Rate            True
100                   False
50                    False
0                     False
4s                    False
6s                    False
dtype: bool

In [7]:
df[df['Balls_Faced'].isna()==1]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Strike_Rate,100,50,0,4s,6s
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,NaN,NaN,15,19,6,258+,2
13,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,NaN,NaN,15,14,1,107+,11
52,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,NaN,NaN,5,6,3,51+,0

In [8]:
df['Balls_Faced'] = df['Balls_Faced'].fillna(0)
df['Strike_Rate'] = df['Strike_Rate'].fillna(0)

In [9]:
df[df['Player']=='CL Walcott (WI)']

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Strike_Rate,100,50,0,4s,6s
13,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,0,0.0,15,14,1,107+,11

In [10]:
df.duplicated()

0     False
1     False
2     False
3      True
4     False
      ...
57    False
58    False
59    False
60    False
61    False
Length: 62, dtype: bool

In [11]:
df[df['Player'].duplicated()==1]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Strike_Rate,100,50,0,4s,6s
3,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
35,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36

In [12]:
df[df['Player'].isin(['AC Voges (AUS)', 'GS Sobers (WI)','S Chanderpaul (WI)' ])]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Strike_Rate,100,50,0,4s,6s
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
10,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
34,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36
35,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36

In [13]:
df = df.drop_duplicates()

In [14]:
df[df['Player'].isin(['AC Voges (AUS)', 'GS Sobers (WI)','S Chanderpaul (WI)' ])]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Strike_Rate,100,50,0,4s,6s
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
10,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
34,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36

In [15]:
df['Span'].str.split(pat = '-')

0     [1928, 1948]
1     [2022, 2025]
2     [2015, 2016]
4     [1930, 1954]
5     [1924, 1935]
6     [1931, 1939]
7     [1955, 1968]
8     [1948, 1958]
9     [1927, 1947]
10    [1954, 1974]
12    [1908, 1930]
13    [1948, 1960]
14    [1937, 1955]
15    [2010, 2026]
16    [1995, 2013]
17    [1921, 1929]
18    [1968, 1973]
19    [1993, 1995]
20    [2010, 2026]
21    [2022, 2026]
22    [1970, 1984]
23    [1935, 1951]
24    [1989, 2013]
25    [1990, 2006]
26    [1976, 1993]
27    [1996, 2012]
28    [1998, 2010]
29    [2000, 2017]
30    [1995, 2012]
31    [1920, 1929]
32    [1992, 2002]
33    [2005, 2013]
34    [1994, 2015]
36    [1985, 2004]
37    [1994, 2009]
38    [2012, 2026]
39    [2004, 2018]
40    [1978, 1994]
41    [1974, 1991]
42    [1937, 1957]
43    [1997, 2014]
44    [1992, 2007]
45    [1948, 1963]
46    [1911, 1928]
47    [2001, 2013]
48    [2019, 2021]
49    [2004, 2015]
50    [1961, 1966]
51    [1929, 1949]
52    [1893, 1905]
53    [2001, 2013]
54    [2023, 2026]
55    [1948, 1963]
56    [1965, 1981]
57    [2002, 2014]
58    [2018, 2026]
59    [1924, 1934]
60    [1930, 1938]
61    [1928, 1934]
Name: Span, dtype: object

In [16]:
df['Span'].str.split(pat = '-').str[1]

0     1948
1     2025
2     2016
4     1954
5     1935
6     1939
7     1968
8     1958
9     1947
10    1974
12    1930
13    1960
14    1955
15    2026
16    2013
17    1929
18    1973
19    1995
20    2026
21    2026
22    1984
23    1951
24    2013
25    2006
26    1993
27    2012
28    2010
29    2017
30    2012
31    1929
32    2002
33    2013
34    2015
36    2004
37    2009
38    2026
39    2018
40    1994
41    1991
42    1957
43    2014
44    2007
45    1963
46    1928
47    2013
48    2021
49    2015
50    1966
51    1949
52    1905
53    2013
54    2026
55    1963
56    1981
57    2014
58    2026
59    1934
60    1938
61    1934
Name: Span, dtype: object

In [17]:
df['Rookie_Year'] = df['Span'].str.split(pat = '-').str[0]

In [18]:
df['Final_Year'] = df['Span'].str.split(pat = '-').str[1]

In [19]:
df = df.drop(['Span'], axis = 1)

In [20]:
df.head()

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948
1,PHKD Mendis (SL),14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,2022,2025
2,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
4,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954
5,H Sutcliffe (ENG),54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935

In [21]:
df['Player'].str.split(pat = '(')

0             [DG Bradman , AUS)]
1             [PHKD Mendis , SL)]
2               [AC Voges , AUS)]
4              [GA Headley , WI)]
5            [H Sutcliffe , ENG)]
6              [E Paynter , ENG)]
7          [KF Barrington , ENG)]
8               [ED Weekes , WI)]
9             [WR Hammond , ENG)]
10              [GS Sobers , WI)]
12              [JB Hobbs , ENG)]
13             [CL Walcott , WI)]
14              [L Hutton , ENG)]
15             [SPD Smith , AUS)]
16          [JH Kallis , ICC/SA)]
17          [GE Tyldesley , ENG)]
18               [CA Davis , WI)]
19             [VG Kambli , IND)]
20          [KS Williamson , NZ)]
21              [HC Brook , ENG)]
22           [GS Chappell , AUS)]
23              [AD Nourse , SA)]
24          [SR Tendulkar , IND)]
25            [BC Lara , ICC/WI)]
26         [Javed Miandad , PAK)]
27          [R Dravid , ICC/IND)]
28       [Mohammad Yousuf , PAK)]
29           [Younis Khan , PAK)]
30            [RT Ponting , AUS)]
31               [J Ryder , AUS)]
32              [A Flower , ZIM)]
33            [MEK Hussey , AUS)]
34          [S Chanderpaul , WI)]
36              [SR Waugh , AUS)]
37             [ML Hayden , AUS)]
38               [JE Root , ENG)]
39         [AB de Villiers , SA)]
40             [AR Border , AUS)]
41           [IVA Richards , WI)]
42           [DCS Compton , ENG)]
43       [DPMD Jayawardene , SL)]
44    [Inzamam-ul-Haq , ICC/PAK)]
45            [FMM Worrell , WI)]
46               [CP Mead , ENG)]
47          [V Sehwag , ICC/IND)]
48              [Abid Ali , PAK)]
49             [MJ Clarke , AUS)]
50               [KC Bland , SA)]
51             [B Mitchell , SA)]
52        [Hon.FS Jackson , ENG)]
53         [TT Samaraweera , SL)]
54           [YBK Jaiswal , IND)]
55             [RN Harvey , AUS)]
56            [KD Walters , AUS)]
57           [GC Smith , ICC/SA)]
58           [Rahmat Shah , AFG)]
59           [WH Ponsford , AUS)]
60             [SJ McCabe , AUS)]
61            [DR Jardine , ENG)]
Name: Player, dtype: object

In [22]:
df['Country'] = df['Player'].str.split(pat = '(').str[1]

In [23]:
df['Country'] = df['Country'].str.split(pat = ')').str[0]

In [24]:
df['Country']

0         AUS
1          SL
2         AUS
4          WI
5         ENG
6         ENG
7         ENG
8          WI
9         ENG
10         WI
12        ENG
13         WI
14        ENG
15        AUS
16     ICC/SA
17        ENG
18         WI
19        IND
20         NZ
21        ENG
22        AUS
23         SA
24        IND
25     ICC/WI
26        PAK
27    ICC/IND
28        PAK
29        PAK
30        AUS
31        AUS
32        ZIM
33        AUS
34         WI
36        AUS
37        AUS
38        ENG
39         SA
40        AUS
41         WI
42        ENG
43         SL
44    ICC/PAK
45         WI
46        ENG
47    ICC/IND
48        PAK
49        AUS
50         SA
51         SA
52        ENG
53         SL
54        IND
55        AUS
56        AUS
57     ICC/SA
58        AFG
59        AUS
60        AUS
61        ENG
Name: Country, dtype: object

In [25]:
df['Player']=df['Player'].str.split(pat = '(').str[0]

In [26]:
df.head()

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS
1,PHKD Mendis,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL
2,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
4,GA Headley,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,WI
5,H Sutcliffe,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,ENG

In [27]:
df.dtypes

Player                 object
Matches                object
Inns                    int64
Not_Outs                int64
Runs                    int64
Highest_Inns_Score     object
Ave                   float64
Balls_Faced            object
Strike_Rate           float64
100                     int64
50                      int64
0                       int64
4s                     object
6s                     object
Rookie_Year            object
Final_Year             object
Country                object
dtype: object

In [28]:
df['Highest_Inns_Score'].str.split(pat = '*').str[0]

0     334
1     182
2     269
4     270
5     194
6     243
7     256
8     207
9     336
10    365
12    211
13    220
14    364
15    239
16    224
17    122
18    183
19    227
20    251
21    317
22    247
23    231
24    248
25    400
26    280
27    270
28    223
29    313
30    257
31    201
32    232
33    195
34    203
36    200
37    380
38    262
39    278
40    205
41    291
42    278
43    374
44    329
45    261
46    182
47    319
48    215
49    329
50    144
51    189
52    144
53    231
54    214
55    205
56    250
57    277
58    234
59    266
60    232
61    127
Name: Highest_Inns_Score, dtype: object

In [29]:
df['Highest_Inns_Score'] = df['Highest_Inns_Score'].str.split(pat = '*').str[0]

In [30]:
df['Highest_Inns_Score'] = df['Highest_Inns_Score'].astype('int')

In [31]:
df.dtypes

Player                 object
Matches                object
Inns                    int64
Not_Outs                int64
Runs                    int64
Highest_Inns_Score      int32
Ave                   float64
Balls_Faced            object
Strike_Rate           float64
100                     int64
50                      int64
0                       int64
4s                     object
6s                     object
Rookie_Year            object
Final_Year             object
Country                object
dtype: object

In [32]:
df=df.astype({'Rookie_Year':'int','Final_Year':'int'})

In [33]:
df.dtypes

Player                 object
Matches                object
Inns                    int64
Not_Outs                int64
Runs                    int64
Highest_Inns_Score      int32
Ave                   float64
Balls_Faced            object
Strike_Rate           float64
100                     int64
50                      int64
0                       int64
4s                     object
6s                     object
Rookie_Year             int32
Final_Year              int32
Country                object
dtype: object

In [34]:
df['Matches'] = df['Matches'].str.split(pat = '*').str[0]

In [35]:
df['Matches'] = df['Matches'].astype('int')

In [36]:
df.dtypes

Player                 object
Matches                 int32
Inns                    int64
Not_Outs                int64
Runs                    int64
Highest_Inns_Score      int32
Ave                   float64
Balls_Faced            object
Strike_Rate           float64
100                     int64
50                      int64
0                       int64
4s                     object
6s                     object
Rookie_Year             int32
Final_Year              int32
Country                object
dtype: object

In [37]:
df['Balls_Faced'] = df['Balls_Faced'].str.split(pat = '+').str[0]

In [38]:
df.isnull().any()

Player                False
Matches               False
Inns                  False
Not_Outs              False
Runs                  False
Highest_Inns_Score    False
Ave                   False
Balls_Faced            True
Strike_Rate           False
100                   False
50                    False
0                     False
4s                    False
6s                    False
Rookie_Year           False
Final_Year            False
Country               False
dtype: bool

In [39]:
df[df['Balls_Faced'].isna()==1]

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
8,ED Weekes,48,81,5,4455,207,58.61,NaN,0.0,15,19,6,258+,2,1948,1958,WI
13,CL Walcott,44,74,7,3798,220,56.68,NaN,0.0,15,14,1,107+,11,1948,1960,WI
52,Hon.FS Jackson,20,33,4,1415,144,48.79,NaN,0.0,5,6,3,51+,0,1893,1905,ENG

In [40]:
df['Balls_Faced'] = df['Balls_Faced'].fillna(0)

In [41]:
df[df['Player']=='ED Weekes ']

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
8,ED Weekes,48,81,5,4455,207,58.61,0,0.0,15,19,6,258+,2,1948,1958,WI

In [42]:
df.isnull().any()

Player                False
Matches               False
Inns                  False
Not_Outs              False
Runs                  False
Highest_Inns_Score    False
Ave                   False
Balls_Faced           False
Strike_Rate           False
100                   False
50                    False
0                     False
4s                    False
6s                    False
Rookie_Year           False
Final_Year            False
Country               False
dtype: bool

In [43]:
pd.set_option('display.max_rows', None)

In [44]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626+,6,1928,1948,AUS
1,PHKD Mendis,14,24,3,1316,182,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
4,GA Headley,22,40,4,2190,270,60.83,416,56.00,10,5,2,104+,1,1930,1954,WI
5,H Sutcliffe,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202+,6,1924,1935,ENG
6,E Paynter,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125+,4,1931,1939,ENG
7,KF Barrington,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591+,27,1955,1968,ENG
8,ED Weekes,48,81,5,4455,207,58.61,0,0.00,15,19,6,258+,2,1948,1958,WI
9,WR Hammond,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419+,27,1927,1947,ENG
10,GS Sobers,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593+,32+,1954,1974,WI
12,JB Hobbs,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276+,8,1908,1930,ENG
13,CL Walcott,44,74,7,3798,220,56.68,0,0.00,15,14,1,107+,11,1948,1960,WI
14,L Hutton,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358+,7,1937,1955,ENG
15,SPD Smith,123,220,28,10763,239,56.05,19966,53.90,37,44,11,1172,67,2010,2026,AUS
16,JH Kallis,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA
17,GE Tyldesley,14,20,2,990,122,55.00,178,29.21,3,6,2,37+,2,1921,1929,ENG
18,CA Davis,15,29,5,1301,183,54.20,665,35.48,4,4,1,65+,1,1968,1973,WI
19,VG Kambli,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND
20,KS Williamson,110,195,19,9515,251,54.06,18306,51.97,33,38,12,1063,28,2010,2026,NZ
21,HC Brook,36,62,2,3234,317,53.90,3735,86.58,10,16,5,349,52,2022,2026,ENG
22,GS Chappell,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,1970,1984,AUS
23,AD Nourse,34,62,7,2960,231,53.81,108,63.88,9,14,3,115+,6,1935,1951,SA
24,SR Tendulkar,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058+,69,1989,2013,IND
25,BC Lara,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI
26,Javed Miandad,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788+,48,1976,1993,PAK
27,R Dravid,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND
28,Mohammad Yousuf,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK
29,Younis Khan,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK
30,RT Ponting,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS
31,J Ryder,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102+,3,1920,1929,AUS
32,A Flower,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM
33,MEK Hussey,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS
34,S Chanderpaul,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI
36,SR Waugh,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS
37,ML Hayden,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS
38,JE Root,164,300,25,13952,262,50.73,24269,57.48,41,66,15,1493,46,2012,2026,ENG
39,AB de Villiers,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA
40,AR Border,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994,AUS
41,IVA Richards,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952+,84,1974,1991,WI
42,DCS Compton,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342+,3,1937,1957,ENG
43,DPMD Jayawardene,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,SL
44,Inzamam-ul-Haq,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,ICC/PAK
45,FMM Worrell,51,87,9,3860,261,49.48,488,40.16,9,22,11,240+,11,1948,1963,WI
46,CP Mead,17,26,2,1185,182,49.37,619,30.04,4,3,3,38+,0,1911,1928,ENG
47,V Sehwag,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,ICC/IND
48,Abid Ali,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,PAK
49,MJ Clarke,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2004,2015,AUS
50,KC Bland,21,39,5,1669,144,49.08,885,37.74,3,9,2,123+,20,1961,1966,SA
51,B Mitchell,42,80,9,3471,189,48.88,158,29.11,8,21,3,41+,1,1929,1949,SA
52,Hon.FS Jackson,20,33,4,1415,144,48.79,0,0.00,5,6,3,51+,0,1893,1905,ENG
53,TT Samaraweera,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,SL
54,YBK Jaiswal,29,54,2,2535,214,48.75,3835,66.10,7,13,6,317,45,2023,2026,IND
55,RN Harvey,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427+,1,1948,1963,AUS
56,KD Walters,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525+,23,1965,1981,AUS
57,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
58,Rahmat Shah,12,22,1,1013,234,48.23,1901,53.28,3,5,4,123,7,2018,2026,AFG
59,WH Ponsford,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119+,0,1924,1934,AUS
60,SJ McCabe,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241+,5+,1930,1938,AUS
61,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53+,0,1928,1934,ENG

In [45]:
df.isnull().any()

Player                False
Matches               False
Inns                  False
Not_Outs              False
Runs                  False
Highest_Inns_Score    False
Ave                   False
Balls_Faced           False
Strike_Rate           False
100                   False
50                    False
0                     False
4s                    False
6s                    False
Rookie_Year           False
Final_Year            False
Country               False
dtype: bool

In [46]:
df.dtypes

Player                 object
Matches                 int32
Inns                    int64
Not_Outs                int64
Runs                    int64
Highest_Inns_Score      int32
Ave                   float64
Balls_Faced            object
Strike_Rate           float64
100                     int64
50                      int64
0                       int64
4s                     object
6s                     object
Rookie_Year             int32
Final_Year              int32
Country                object
dtype: object

In [47]:
df['Balls_Faced'] = df['Balls_Faced'].astype('int')

In [48]:
df.dtypes

Player                 object
Matches                 int32
Inns                    int64
Not_Outs                int64
Runs                    int64
Highest_Inns_Score      int32
Ave                   float64
Balls_Faced             int32
Strike_Rate           float64
100                     int64
50                      int64
0                       int64
4s                     object
6s                     object
Rookie_Year             int32
Final_Year              int32
Country                object
dtype: object

In [49]:
df['4s'] = df['4s'].str.replace('+', '', regex=False)

In [50]:
df['4s'] = df['4s'].astype('int')

In [51]:
df['6s'] = df['6s'].str.split(pat = '+').str[0]

In [52]:
df['6s'] = df['6s'].astype('int')

In [53]:
df.dtypes

Player                 object
Matches                 int32
Inns                    int64
Not_Outs                int64
Runs                    int64
Highest_Inns_Score      int32
Ave                   float64
Balls_Faced             int32
Strike_Rate           float64
100                     int64
50                      int64
0                       int64
4s                      int32
6s                      int32
Rookie_Year             int32
Final_Year              int32
Country                object
dtype: object

In [54]:
df['career_length'] = df['Final_Year'] - df['Rookie_Year']

In [55]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country,career_length
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948,AUS,20
1,PHKD Mendis,14,24,3,1316,182,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL,3
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS,1
4,GA Headley,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1930,1954,WI,24
5,H Sutcliffe,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,1924,1935,ENG,11
6,E Paynter,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,1931,1939,ENG,8
7,KF Barrington,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,1955,1968,ENG,13
8,ED Weekes,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958,WI,10
9,WR Hammond,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,1927,1947,ENG,20
10,GS Sobers,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32,1954,1974,WI,20
12,JB Hobbs,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,1908,1930,ENG,22
13,CL Walcott,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1948,1960,WI,12
14,L Hutton,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,1937,1955,ENG,18
15,SPD Smith,123,220,28,10763,239,56.05,19966,53.90,37,44,11,1172,67,2010,2026,AUS,16
16,JH Kallis,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA,18
17,GE Tyldesley,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,1921,1929,ENG,8
18,CA Davis,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1,1968,1973,WI,5
19,VG Kambli,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND,2
20,KS Williamson,110,195,19,9515,251,54.06,18306,51.97,33,38,12,1063,28,2010,2026,NZ,16
21,HC Brook,36,62,2,3234,317,53.90,3735,86.58,10,16,5,349,52,2022,2026,ENG,4
22,GS Chappell,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,1970,1984,AUS,14
23,AD Nourse,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,1935,1951,SA,16
24,SR Tendulkar,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,1989,2013,IND,24
25,BC Lara,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI,16
26,Javed Miandad,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,1976,1993,PAK,17
27,R Dravid,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND,16
28,Mohammad Yousuf,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK,12
29,Younis Khan,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK,17
30,RT Ponting,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS,17
31,J Ryder,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,1920,1929,AUS,9
32,A Flower,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM,10
33,MEK Hussey,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS,8
34,S Chanderpaul,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI,21
36,SR Waugh,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS,19
37,ML Hayden,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS,15
38,JE Root,164,300,25,13952,262,50.73,24269,57.48,41,66,15,1493,46,2012,2026,ENG,14
39,AB de Villiers,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA,14
40,AR Border,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994,AUS,16
41,IVA Richards,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,1974,1991,WI,17
42,DCS Compton,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,1937,1957,ENG,20
43,DPMD Jayawardene,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,SL,17
44,Inzamam-ul-Haq,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,ICC/PAK,15
45,FMM Worrell,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,1948,1963,WI,15
46,CP Mead,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,1911,1928,ENG,17
47,V Sehwag,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,ICC/IND,12
48,Abid Ali,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,PAK,2
49,MJ Clarke,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2004,2015,AUS,11
50,KC Bland,21,39,5,1669,144,49.08,885,37.74,3,9,2,123,20,1961,1966,SA,5
51,B Mitchell,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,1929,1949,SA,20
52,Hon.FS Jackson,20,33,4,1415,144,48.79,0,0.00,5,6,3,51,0,1893,1905,ENG,12
53,TT Samaraweera,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,SL,12
54,YBK Jaiswal,29,54,2,2535,214,48.75,3835,66.10,7,13,6,317,45,2023,2026,IND,3
55,RN Harvey,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,1948,1963,AUS,15
56,KD Walters,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1965,1981,AUS,16
57,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA,12
58,Rahmat Shah,12,22,1,1013,234,48.23,1901,53.28,3,5,4,123,7,2018,2026,AFG,8
59,WH Ponsford,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,AUS,10
60,SJ McCabe,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1930,1938,AUS,8
61,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,ENG,6

In [56]:
df['career_length'].mean()

13.203389830508474

In [57]:
df[df['career_length'] > 10]['Strike_Rate'].mean()

47.76780487804878

In [58]:
df[df['Rookie_Year'] < 1960]['Player'].count()

23

In [59]:
df.groupby('Country')['Highest_Inns_Score'].max().to_frame('Highinncountry').reset_index().sort_values('Highinncountry', ascending = False)

    Country  Highinncountry
6    ICC/WI             400
1       AUS             380
11       SL             374
12       WI             365
2       ENG             364
4   ICC/PAK             329
3   ICC/IND             319
9       PAK             313
10       SA             278
5    ICC/SA             277
8        NZ             251
7       IND             248
0       AFG             234
13      ZIM             232

In [60]:
df.groupby('Country')[['100', '50', '0']].mean()

               100         50          0
Country
AFG       3.000000   5.000000   4.000000
AUS      21.600000  29.133333   8.933333
ENG      13.615385  21.923077   4.846154
ICC/IND  29.500000  47.500000  12.000000
ICC/PAK  25.000000  46.000000  15.000000
ICC/SA   36.000000  48.000000  13.500000
ICC/WI   34.000000  48.000000  17.000000
IND      20.666667  28.000000   7.666667
NZ       33.000000  38.000000  12.000000
PAK      21.250000  28.000000   9.500000
SA       10.500000  22.500000   4.000000
SL       17.666667  28.333333   8.666667
WI       16.625000  25.625000   7.250000
ZIM      12.000000  27.000000   5.000000